#!/bin/bash

vim_navigation_timeout=0.05 # number of seconds we give Vim to navigate

pane_title="#{q:pane_title}"

pane_current_command="#{q:pane_current_command}"

pane_is_zoomed() {
  test #{window_zoomed_flag} -eq 1
}

pane_title_changed() {
  test "$pane_title" != "$(tmux display -p "##{q:pane_title}")"
}

command_is_vim() {
  case "${1%% *}" in
    (vi|?vi|vim*|?vim*|view|?view|vi??*) true ;;
    (*) false ;;
  esac
}

pane_contains_vim() {
  case "$pane_current_command" in
    (git|*sh) command_is_vim "$pane_title" ;;
    (*) command_is_vim "$pane_current_command" ;;
  esac
}

pane_contains_neovim_terminal() {
  case "$pane_title" in
    (nvim?term://*) true ;;
    (*) false ;;
  esac
}

navigate() {
  tmux_navigation_command=$1
  vim_navigation_command=$2
  vim_navigation_only_if=${3:-true}
  if pane_contains_vim && eval "$vim_navigation_only_if"; then
    if pane_contains_neovim_terminal; then
      tmux send-keys C-\\ C-n
    fi
    eval "$vim_navigation_command"
    if ! pane_is_zoomed; then
      sleep $vim_navigation_timeout
      if ! pane_title_changed; then
        tmux send-keys BSpace
        eval "$tmux_navigation_command"
      fi
    fi
  elif ! pane_is_zoomed; then
    eval "$tmux_navigation_command"
  fi
}

